# Generated by Django 4.2.4 on 2024-01-16 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_front'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carasol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_images', models.ImageField(null=True, upload_to='uploads/products/')),
            ],
        ),
    ]
