# Generated by Django 4.2.4 on 2024-01-16 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_carasol'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carasol',
        ),
    ]
